Update DocumentToFlat.java
Fixed error when moving from dom4j-1.6.1 to dom4j-2.0.0.
error: incompatible types: List<Node> cannot be converted to List<AbstractNode>
nodes = loopXpath.selectNodes(doc);

https://jira.talendforge.org/browse/TDI-40133